# Generated by Django 5.2 on 2025-06-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
