# Generated by Django 5.2 on 2025-07-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductReview",
        ),
    ]
